### ISSUE TITLE
Updating `items` after component creation breaks filtering

### ISSUE THREAD

**Issue by stephenlrandall** [rob-balfre/svelte-select#274]
REPL demo: https://svelte.dev/repl/7d340b2dd3f94a2a93c4be91476f3a3c?version=3.20.1

Essentially, because `originalItemsClone` is set on component creation and not reactively updated, changing `items` after initialization breaks the filtering because the items are compared to the incorrect set of original items.

**Comment by rob-balfre** [comment]
eek!  Thanks, will investigate.

**Comment by rob-balfre** [comment]
Fixed in v4.2.2

https://svelte.dev/repl/8e199efac46c43b6946fa9bfb64a51ba?version=3.20.1

**Comment by stephenlrandall** [comment]
@rob-balfre Thanks for the quick work! Unfortunately it looks like there's still an issue for grouped items: https://svelte.dev/repl/183b491358ad470e868a8de5c781fa3d?version=3.20.1

**Comment by rob-balfre** [comment]
Nice find - getting better test coverage fixing these!

**Comment by rob-balfre** [comment]
Does `svelte-select@4.2.3-beta.2` solve your issues?

**Comment by stephenlrandall** [comment]
@rob-balfre It seems like it does! I'll let you know if we have any other issues.

**Comment by rob-balfre** [comment]
Will release a version later today hopefully.

If anything other issues pop up from that beta let me know. Thanks again.

**Comment by rob-balfre** [comment]
svelte-select@4.2.3 released
