### ISSUE TITLE
A11y: on:mouseover must be accompanied by on:focus with Svelte v3.40

### ISSUE THREAD

**Issue by evdama** [rob-balfre/svelte-select#285]
I've upgraded Svelte to v3.40 and now my build breaks with this error:

```
node_modules/.pnpm/svelte-select@4.2.7-beta.0/node_modules/svelte-select/src/List.svelte
A11y: on:mouseover must be accompanied by on:focus
285:             let:item
286:             let:i>
287:             <div
                 ^
288:                 on:mouseover={() => handleHover(i)}
289:                 on:click={(event) => handleClick({ item, i, event })}
node_modules/.pnpm/svelte-select@4.2.7-beta.0/node_modules/svelte-select/src/List.svelte
A11y: on:mouseover must be accompanied by on:focus
308:                 <div class="listGroupTitle">{getGroupHeaderLabel(item)}</div>
309:             {:else}
310:                 <div
                     ^
311:                     on:mouseover={() => handleHover(i)}
312:                     on:click={(event) => handleClick({ item, i, event })}
```

@rob-balfre this is with 4.2.7-beta.0 as well as 4.2.6 🤷‍♂️

**Comment by rob-balfre** [comment]
@evdama thanks for reporting.

Fixed in v4.2.7

**Comment by derkphi** [comment]
I still have this error with svelte v3.46.4. I am wondering which module I have to update to get rid of that error since v4.2.7 seams out of scope for svelte to me.

**Comment by pasevin** [comment]
Is there a solution for this for version `3.49.0` ?

**Comment by petrosoft-fi** [comment]
No error if you just add `on:focus={}`. Although then you also have to add `on:blur{}`. In the end we get some boilerplate code...

```
    <header 
        class:solidBg={isSolid} 
        on:mouseover={changeSolid} 
        on:mouseout={changeSolid} 
        on:focus={changeSolid} 
        on:blur={changeSolid}
    >
```
