### ISSUE TITLE
List automatically opened

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#548]
As you can see in the below REPL if I render the Modal component (toggling it with the button) the list is not automatically opened (using `listOpen={true}`):

https://svelte.dev/repl/0e50e79784b04ed8a9f22244b5f36d13?version=3.55.1

Am I wrong?

![image](https://user-images.githubusercontent.com/41120635/217912331-0182335a-08af-4848-8c9c-42cfdeff4945.png)

**Comment by rob-balfre** [comment]
Fixed in `5.3.0`

**Comment by geoidesic** [comment]
Is it though? I'm still getting this in v5.8.3. Basically `listOpen` doesn't seem to do anything. Even on the REPL it's intermittent – seems to work until you click in the code editor, then it vanishes. On my own implementation it doesn't work at all, which makes debugging overflow CSS nearly impossible.

**Comment by geoidesic** [comment]
This OP's link still doesn't open it: https://svelte.dev/repl/0e50e79784b04ed8a9f22244b5f36d13?version=3.55.1
